language: python
cache: pip
dist: bionic
sudo: false
python:
  - "3.8"
  - "3.9"

install:
  - travis_retry pip install -U tox-travis
  - pip install .
  - pip install aiofiles coverage pytest
script:
  - tox
after_success:
  - pip install codecov
  - codecov
notifications:
    email: false
