language: python
cache: pip
python:
  - "3.8"
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install .
  - pip install pytest coverage
script: coverage run -m pytest
after_success:
  - pip install codecov
  - codecov
